// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: match_turns.sql

package store

import (
	"context"
)

const createMatchTurn = `-- name: CreateMatchTurn :one
INSERT INTO match_turns (
    match_id,
    turn_number,
    acting_player_id,
    acting_match_unit_id,
    move_id,
    target_match_unit_id,
    damage_done,
    target_hp_after,
    did_ko_target
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING
    id,
    match_id,
    turn_number,
    acting_player_id,
    acting_match_unit_id,
    move_id,
    target_match_unit_id,
    damage_done,
    target_hp_after,
    did_ko_target,
    created_at
`

type CreateMatchTurnParams struct {
	MatchID           int64
	TurnNumber        int32
	ActingPlayerID    int64
	ActingMatchUnitID int64
	MoveID            int64
	TargetMatchUnitID int64
	DamageDone        int32
	TargetHpAfter     int32
	DidKoTarget       bool
}

func (q *Queries) CreateMatchTurn(ctx context.Context, arg CreateMatchTurnParams) (MatchTurn, error) {
	row := q.db.QueryRowContext(ctx, createMatchTurn,
		arg.MatchID,
		arg.TurnNumber,
		arg.ActingPlayerID,
		arg.ActingMatchUnitID,
		arg.MoveID,
		arg.TargetMatchUnitID,
		arg.DamageDone,
		arg.TargetHpAfter,
		arg.DidKoTarget,
	)
	var i MatchTurn
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.TurnNumber,
		&i.ActingPlayerID,
		&i.ActingMatchUnitID,
		&i.MoveID,
		&i.TargetMatchUnitID,
		&i.DamageDone,
		&i.TargetHpAfter,
		&i.DidKoTarget,
		&i.CreatedAt,
	)
	return i, err
}

const listMatchTurns = `-- name: ListMatchTurns :many
SELECT
  id, match_id, turn_number, acting_player_id,
  acting_match_unit_id, move_id, target_match_unit_id,
  damage_done, target_hp_after, did_ko_target, created_at
FROM match_turns
WHERE match_id = $1
ORDER BY turn_number
`

func (q *Queries) ListMatchTurns(ctx context.Context, matchID int64) ([]MatchTurn, error) {
	rows, err := q.db.QueryContext(ctx, listMatchTurns, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MatchTurn
	for rows.Next() {
		var i MatchTurn
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.TurnNumber,
			&i.ActingPlayerID,
			&i.ActingMatchUnitID,
			&i.MoveID,
			&i.TargetMatchUnitID,
			&i.DamageDone,
			&i.TargetHpAfter,
			&i.DidKoTarget,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
