// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: match_units.sql

package store

import (
	"context"
)

const createMatchUnit = `-- name: CreateMatchUnit :one
INSERT INTO match_units (
    match_side_id,
    unit_id,
    position,
    current_hp
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, match_side_id, unit_id, position, current_hp
`

type CreateMatchUnitParams struct {
	MatchSideID int64
	UnitID      int64
	Position    int32
	CurrentHp   int32
}

func (q *Queries) CreateMatchUnit(ctx context.Context, arg CreateMatchUnitParams) (MatchUnit, error) {
	row := q.db.QueryRowContext(ctx, createMatchUnit,
		arg.MatchSideID,
		arg.UnitID,
		arg.Position,
		arg.CurrentHp,
	)
	var i MatchUnit
	err := row.Scan(
		&i.ID,
		&i.MatchSideID,
		&i.UnitID,
		&i.Position,
		&i.CurrentHp,
	)
	return i, err
}

const getActiveMatchUnitForSide = `-- name: GetActiveMatchUnitForSide :one
SELECT mu.id, mu.match_side_id, mu.unit_id, mu.position, mu.current_hp
FROM match_units mu
JOIN match_sides ms ON ms.id = mu.match_side_id
WHERE mu.match_side_id = $1
  AND mu.position = ms.active_index
`

func (q *Queries) GetActiveMatchUnitForSide(ctx context.Context, matchSideID int64) (MatchUnit, error) {
	row := q.db.QueryRowContext(ctx, getActiveMatchUnitForSide, matchSideID)
	var i MatchUnit
	err := row.Scan(
		&i.ID,
		&i.MatchSideID,
		&i.UnitID,
		&i.Position,
		&i.CurrentHp,
	)
	return i, err
}

const getMatchUnitsBySideID = `-- name: GetMatchUnitsBySideID :many
SELECT
    id, match_side_id, unit_id, position, current_hp
FROM match_units
WHERE match_side_id = $1
ORDER BY position
`

func (q *Queries) GetMatchUnitsBySideID(ctx context.Context, matchSideID int64) ([]MatchUnit, error) {
	rows, err := q.db.QueryContext(ctx, getMatchUnitsBySideID, matchSideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MatchUnit
	for rows.Next() {
		var i MatchUnit
		if err := rows.Scan(
			&i.ID,
			&i.MatchSideID,
			&i.UnitID,
			&i.Position,
			&i.CurrentHp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMatchUnitHP = `-- name: UpdateMatchUnitHP :one
UPDATE match_units
SET current_hp = $2
WHERE id = $1
RETURNING id, match_side_id, unit_id, position, current_hp
`

type UpdateMatchUnitHPParams struct {
	ID        int64
	CurrentHp int32
}

func (q *Queries) UpdateMatchUnitHP(ctx context.Context, arg UpdateMatchUnitHPParams) (MatchUnit, error) {
	row := q.db.QueryRowContext(ctx, updateMatchUnitHP, arg.ID, arg.CurrentHp)
	var i MatchUnit
	err := row.Scan(
		&i.ID,
		&i.MatchSideID,
		&i.UnitID,
		&i.Position,
		&i.CurrentHp,
	)
	return i, err
}
