// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: match_sides.sql

package store

import (
	"context"
)

const createMatchSide = `-- name: CreateMatchSide :one
INSERT INTO match_sides (
    match_id,
    player_id,
    squad_id,
    active_index
) VALUES (
    $1, $2, $3, 0
)
RETURNING id, match_id, player_id, squad_id, active_index
`

type CreateMatchSideParams struct {
	MatchID  int64
	PlayerID int64
	SquadID  int64
}

func (q *Queries) CreateMatchSide(ctx context.Context, arg CreateMatchSideParams) (MatchSide, error) {
	row := q.db.QueryRowContext(ctx, createMatchSide, arg.MatchID, arg.PlayerID, arg.SquadID)
	var i MatchSide
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.PlayerID,
		&i.SquadID,
		&i.ActiveIndex,
	)
	return i, err
}

const getMatchSidesByMatchID = `-- name: GetMatchSidesByMatchID :many
SELECT
    id, match_id, player_id, squad_id, active_index
FROM match_sides
WHERE match_id = $1
`

func (q *Queries) GetMatchSidesByMatchID(ctx context.Context, matchID int64) ([]MatchSide, error) {
	rows, err := q.db.QueryContext(ctx, getMatchSidesByMatchID, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MatchSide
	for rows.Next() {
		var i MatchSide
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.PlayerID,
			&i.SquadID,
			&i.ActiveIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMatchSideActiveIndex = `-- name: UpdateMatchSideActiveIndex :one
UPDATE match_sides
SET active_index = $2
WHERE id = $1
RETURNING id, match_id, player_id, squad_id, active_index
`

type UpdateMatchSideActiveIndexParams struct {
	ID          int64
	ActiveIndex int32
}

func (q *Queries) UpdateMatchSideActiveIndex(ctx context.Context, arg UpdateMatchSideActiveIndexParams) (MatchSide, error) {
	row := q.db.QueryRowContext(ctx, updateMatchSideActiveIndex, arg.ID, arg.ActiveIndex)
	var i MatchSide
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.PlayerID,
		&i.SquadID,
		&i.ActiveIndex,
	)
	return i, err
}
