// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"time"
)

type Match struct {
	ID                   int64
	State                string
	CreatedAt            time.Time
	StartedAt            sql.NullTime
	CompletedAt          sql.NullTime
	Player1ID            int64
	Player2ID            int64
	WinnerPlayerID       sql.NullInt64
	CurrentTurnNumber    int32
	CurrentActorPlayerID sql.NullInt64
}

type MatchSide struct {
	ID          int64
	MatchID     int64
	PlayerID    int64
	SquadID     int64
	ActiveIndex int32
}

type MatchTurn struct {
	ID                int64
	MatchID           int64
	TurnNumber        int32
	ActingPlayerID    int64
	ActingMatchUnitID int64
	MoveID            int64
	TargetMatchUnitID int64
	DamageDone        int32
	TargetHpAfter     int32
	DidKoTarget       bool
	CreatedAt         time.Time
}

type MatchUnit struct {
	ID          int64
	MatchSideID int64
	UnitID      int64
	Position    int32
	CurrentHp   int32
}

type Move struct {
	ID       int64
	Name     string
	Power    int32
	Accuracy int32
	TypeID   int64
}

type Player struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    time.Time
}

type Squad struct {
	ID        int64
	PlayerID  int64
	Name      string
	CreatedAt time.Time
}

type SquadUnit struct {
	ID       int64
	SquadID  int64
	UnitID   int64
	Position int32
}

type Unit struct {
	ID         int64
	Name       string
	TypeID     int64
	BaseHp     int32
	BaseAttack int32
	BaseSpeed  int32
}

type UnitMove struct {
	UnitID int64
	MoveID int64
}

type UnitType struct {
	ID   int64
	Name string
}
