// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moves.sql

package store

import (
	"context"
)

const listMovesForUnit = `-- name: ListMovesForUnit :many
SELECT
  m.id, m.name, m.power, m.accuracy, m.type_id
FROM moves m
JOIN unit_moves um ON um.move_id = m.id
WHERE um.unit_id = $1
ORDER BY m.id
`

func (q *Queries) ListMovesForUnit(ctx context.Context, unitID int64) ([]Move, error) {
	rows, err := q.db.QueryContext(ctx, listMovesForUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Move
	for rows.Next() {
		var i Move
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Power,
			&i.Accuracy,
			&i.TypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
