// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moves.sql

package store

import (
	"context"
)

const createMove = `-- name: CreateMove :one
INSERT INTO moves (name, power, accuracy, type_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, power, accuracy, type_id
`

type CreateMoveParams struct {
	Name     string
	Power    int32
	Accuracy int32
	TypeID   int64
}

func (q *Queries) CreateMove(ctx context.Context, arg CreateMoveParams) (Move, error) {
	row := q.db.QueryRowContext(ctx, createMove,
		arg.Name,
		arg.Power,
		arg.Accuracy,
		arg.TypeID,
	)
	var i Move
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Power,
		&i.Accuracy,
		&i.TypeID,
	)
	return i, err
}

const createUnitMove = `-- name: CreateUnitMove :one
INSERT INTO unit_moves (unit_id, move_id)
VALUES ($1, $2)
RETURNING unit_id, move_id
`

type CreateUnitMoveParams struct {
	UnitID int64
	MoveID int64
}

func (q *Queries) CreateUnitMove(ctx context.Context, arg CreateUnitMoveParams) (UnitMove, error) {
	row := q.db.QueryRowContext(ctx, createUnitMove, arg.UnitID, arg.MoveID)
	var i UnitMove
	err := row.Scan(&i.UnitID, &i.MoveID)
	return i, err
}

const listMovesForUnit = `-- name: ListMovesForUnit :many
SELECT
  m.id, m.name, m.power, m.accuracy, m.type_id
FROM moves m
JOIN unit_moves um ON um.move_id = m.id
WHERE um.unit_id = $1
ORDER BY m.id
`

func (q *Queries) ListMovesForUnit(ctx context.Context, unitID int64) ([]Move, error) {
	rows, err := q.db.QueryContext(ctx, listMovesForUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Move
	for rows.Next() {
		var i Move
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Power,
			&i.Accuracy,
			&i.TypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
