// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package store

import (
	"context"
	"time"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (username, password_hash)
VALUES ($1, $2)
RETURNING id, username, password_hash, created_at
`

type CreatePlayerParams struct {
	Username     string
	PasswordHash string
}

type CreatePlayerRow struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    time.Time
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (CreatePlayerRow, error) {
	row := q.db.QueryRowContext(ctx, createPlayer, arg.Username, arg.PasswordHash)
	var i CreatePlayerRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, username, password_hash, created_at, is_admin
FROM players
WHERE id = $1
`

func (q *Queries) GetPlayerByID(ctx context.Context, id int64) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const getPlayerByUsername = `-- name: GetPlayerByUsername :one
SELECT id, username, password_hash, created_at
FROM players
WHERE username = $1
`

type GetPlayerByUsernameRow struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    time.Time
}

func (q *Queries) GetPlayerByUsername(ctx context.Context, username string) (GetPlayerByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByUsername, username)
	var i GetPlayerByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
