// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: squads.sql

package store

import (
	"context"
)

const createSquad = `-- name: CreateSquad :one
INSERT INTO squads (
    player_id,
    name
) VALUES (
    $1, $2
)
RETURNING id, player_id, name, created_at
`

type CreateSquadParams struct {
	PlayerID int64
	Name     string
}

func (q *Queries) CreateSquad(ctx context.Context, arg CreateSquadParams) (Squad, error) {
	row := q.db.QueryRowContext(ctx, createSquad, arg.PlayerID, arg.Name)
	var i Squad
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getSquadsForPlayer = `-- name: GetSquadsForPlayer :many
SELECT id, player_id, name, created_at
FROM squads
WHERE player_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetSquadsForPlayer(ctx context.Context, playerID int64) ([]Squad, error) {
	rows, err := q.db.QueryContext(ctx, getSquadsForPlayer, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Squad
	for rows.Next() {
		var i Squad
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
