// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: squad_units.sql

package store

import (
	"context"
)

const createSquadUnit = `-- name: CreateSquadUnit :one
INSERT INTO squad_units (
    squad_id,
    unit_id,
    position
) VALUES (
    $1, $2, $3
)
RETURNING id, squad_id, unit_id, position
`

type CreateSquadUnitParams struct {
	SquadID  int64
	UnitID   int64
	Position int32
}

func (q *Queries) CreateSquadUnit(ctx context.Context, arg CreateSquadUnitParams) (SquadUnit, error) {
	row := q.db.QueryRowContext(ctx, createSquadUnit, arg.SquadID, arg.UnitID, arg.Position)
	var i SquadUnit
	err := row.Scan(
		&i.ID,
		&i.SquadID,
		&i.UnitID,
		&i.Position,
	)
	return i, err
}

const getSquadUnits = `-- name: GetSquadUnits :many
SELECT id, squad_id, unit_id, position
FROM squad_units
WHERE squad_id = $1
ORDER BY position
`

func (q *Queries) GetSquadUnits(ctx context.Context, squadID int64) ([]SquadUnit, error) {
	rows, err := q.db.QueryContext(ctx, getSquadUnits, squadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SquadUnit
	for rows.Next() {
		var i SquadUnit
		if err := rows.Scan(
			&i.ID,
			&i.SquadID,
			&i.UnitID,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
