// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: units.sql

package store

import (
	"context"
)

const getUnitByID = `-- name: GetUnitByID :one
SELECT
  id, name, type_id, base_hp, base_attack, base_speed
FROM units
WHERE id = $1
`

func (q *Queries) GetUnitByID(ctx context.Context, id int64) (Unit, error) {
	row := q.db.QueryRowContext(ctx, getUnitByID, id)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TypeID,
		&i.BaseHp,
		&i.BaseAttack,
		&i.BaseSpeed,
	)
	return i, err
}

const listUnits = `-- name: ListUnits :many
SELECT
  id, name, type_id, base_hp, base_attack, base_speed
FROM units
ORDER BY id
`

func (q *Queries) ListUnits(ctx context.Context) ([]Unit, error) {
	rows, err := q.db.QueryContext(ctx, listUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Unit
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TypeID,
			&i.BaseHp,
			&i.BaseAttack,
			&i.BaseSpeed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
